// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserWebCRUD.Server;

namespace UsuarioWebCRUD.Server.Migrations
{
    [DbContext(typeof(UserProfessionDbContext))]
    [Migration("20210213221125_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserWebCRUD.Shared.ProfessionInfo", b =>
                {
                    b.Property<int>("ProfessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProfessionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfessionId");

                    b.ToTable("ProfessionsInfo");
                });

            modelBuilder.Entity("UserWebCRUD.Shared.UserInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UsersInfo");
                });

            modelBuilder.Entity("UserWebCRUD.Shared.UserProfessionInfo", b =>
                {
                    b.Property<int>("UserProfessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProfessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessionsInfoProfessionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersInfoUserId")
                        .HasColumnType("int");

                    b.HasKey("UserProfessionId");

                    b.HasIndex("ProfessionsInfoProfessionId");

                    b.HasIndex("UsersInfoUserId");

                    b.ToTable("UserProfessionsInfo");
                });

            modelBuilder.Entity("UserWebCRUD.Shared.UserProfessionInfo", b =>
                {
                    b.HasOne("UserWebCRUD.Shared.ProfessionInfo", "ProfessionsInfo")
                        .WithMany("UserProfessionsInfo")
                        .HasForeignKey("ProfessionsInfoProfessionId");

                    b.HasOne("UserWebCRUD.Shared.UserInfo", "UsersInfo")
                        .WithMany("UserProfessionsInfo")
                        .HasForeignKey("UsersInfoUserId");

                    b.Navigation("ProfessionsInfo");

                    b.Navigation("UsersInfo");
                });

            modelBuilder.Entity("UserWebCRUD.Shared.ProfessionInfo", b =>
                {
                    b.Navigation("UserProfessionsInfo");
                });

            modelBuilder.Entity("UserWebCRUD.Shared.UserInfo", b =>
                {
                    b.Navigation("UserProfessionsInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
